FROM node:lts

WORKDIR /app

COPY ./package.json .
RUN npm install

COPY . .

RUN npm run prisma:postgres
RUN npx prisma migrate deploy --schema /app/schemas/postgres.prisma
RUN npm run install-system

CMD npm start

EXPOSE 3000
