DROP TABLE IF EXISTS practices;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS bases;
DROP TABLE IF EXISTS legal_forms;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS contracts;
DROP TABLE IF EXISTS directions;
DROP TABLE IF EXISTS persons;
DROP TABLE IF EXISTS dates;

DROP TYPE  IF EXISTS PERSONTYPE; 
DROP TYPE  IF EXISTS PRACTICETYPE; 
